USE [master]
GO

/****** Object:  Database [depoBakiye]    Script Date: 28.03.2024 12:07:07 ******/
CREATE DATABASE [depoBakiye]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'depoBakiye', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\depoBakiye.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'depoBakiye_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\depoBakiye_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [depoBakiye].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [depoBakiye] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [depoBakiye] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [depoBakiye] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [depoBakiye] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [depoBakiye] SET ARITHABORT OFF 
GO

ALTER DATABASE [depoBakiye] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [depoBakiye] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [depoBakiye] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [depoBakiye] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [depoBakiye] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [depoBakiye] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [depoBakiye] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [depoBakiye] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [depoBakiye] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [depoBakiye] SET  ENABLE_BROKER 
GO

ALTER DATABASE [depoBakiye] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [depoBakiye] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [depoBakiye] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [depoBakiye] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [depoBakiye] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [depoBakiye] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [depoBakiye] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [depoBakiye] SET RECOVERY FULL 
GO

ALTER DATABASE [depoBakiye] SET  MULTI_USER 
GO

ALTER DATABASE [depoBakiye] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [depoBakiye] SET DB_CHAINING OFF 
GO

ALTER DATABASE [depoBakiye] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [depoBakiye] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [depoBakiye] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [depoBakiye] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [depoBakiye] SET QUERY_STORE = OFF
GO

ALTER DATABASE [depoBakiye] SET  READ_WRITE 
GO

